# Generated by Django 4.2.19 on 2025-02-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organization',
            table='organizations',
        ),
    ]
