# Generated by Django 4.2.19 on 2025-02-12 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_code', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('inland port', 'Inland Port'), ('sea port', 'Sea Port')], default='sea port', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ports',
            },
        ),
        migrations.CreateModel(
            name='Yard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yard_name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('geo_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'yards',
            },
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField()),
                ('estimated_travel_time', models.PositiveIntegerField(help_text='Estimated travel time in days or hours')),
                ('lane_status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('closed', 'Closed')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_ports', to='ports.port')),
                ('to_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_ports', to='ports.port')),
            ],
            options={
                'db_table': 'lanes',
            },
        ),
    ]
