# Generated by Django 4.2.19 on 2025-02-11 06:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0003_yard_port_city_port_code_port_geo_code_port_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='country',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
