# Generated by Django 4.2.19 on 2025-02-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0003_alter_lane_id_alter_port_id_alter_yard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
