# Generated by Django 4.2.19 on 2025-02-11 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0005_alter_port_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('lane_id', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.PositiveIntegerField()),
                ('estimated_travel_time', models.PositiveIntegerField(help_text='Estimated travel time in days or hours')),
                ('lane_status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('closed', 'Closed')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_ports', to='ports.port')),
                ('to_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_ports', to='ports.port')),
            ],
            options={
                'db_table': 'lanes',
            },
        ),
    ]
