# Generated by Django 4.2.19 on 2025-02-16 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping', '0004_alter_ship_id_alter_shippingliner_id_and_more'),
        ('ports', '0003_alter_lane_id_alter_port_id_alter_yard_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='draft', max_length=50)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cargo.cargo')),
                ('lane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='ports.lane')),
                ('shipping_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='shipping.shippingroutes')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='initiated', max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tracking',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('bill_of_lading', 'Bill of Lading'), ('freight_invoice', 'Freight Invoice'), ('customs_declaration', 'Customs Declaration'), ('certificate_of_origin', 'Certificate of Origin'), ('insurance_certificate', 'Insurance Certificate'), ('packing_list', 'Packing List'), ('proof_of_delivery', 'Proof of Delivery (POD)'), ('booking_confirmation', 'Booking Confirmation'), ('commercial_invoice', 'Commercial Invoice'), ('special_handling_instructions', 'Special Handling Instructions')], max_length=50)),
                ('document_url', models.CharField(blank=True, max_length=500, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='booking.booking')),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='tracking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='booking.tracking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
