# Generated by Django 4.2.19 on 2025-02-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_document_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('booked', 'Booked'), ('in_transit', 'In Transit'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='draft', max_length=50),
        ),
    ]
