# Generated by Django 4.2.19 on 2025-02-15 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_tracking_booking_tracking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='tracking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracking',
            name='estimated_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
