# Generated by Django 4.2.19 on 2025-02-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_arrange_container_haulage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('order_received', 'Order Received'), ('order_preparing', 'Order Being Prepared'), ('order_dispatched', 'Order Dispatched'), ('in_transit', 'Order in Transit'), ('arrived', 'Order Arrived'), ('delivered', 'Order Delivered'), ('cancelled', 'Order Cancelled')], default='initiated', max_length=50),
        ),
    ]
