# Generated by Django 4.2.19 on 2025-03-01 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_arrangecontaineryardhaulage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrange_container_haulage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.arrangecontaineryardhaulage'),
        ),
    ]
