# Generated by Django 4.2.19 on 2025-03-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_optional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='stakeholders',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
