# Generated by Django 4.2.19 on 2025-03-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_booking_stakeholders'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='arrangecontaineryardhaulage',
            table='arrange_container_yard_haulage',
        ),
        migrations.AlterModelTable(
            name='optionalfields',
            table='optional_fields',
        ),
    ]
