# Generated by Django 4.2.19 on 2025-03-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_arrangecontaineryardhaulage_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='optional_fields',
        ),
        migrations.AddField(
            model_name='booking',
            name='optional_fields',
            field=models.ManyToManyField(blank=True, to='booking.optionalfields'),
        ),
    ]
