# Generated by Django 5.1.6 on 2025-03-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_remove_booking_optional_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('order_booked', 'Order Booked'), ('order_confirmed', 'Order Confirmed'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Order Cancelled')], default='initiated', max_length=50),
        ),
    ]
