# Generated by Django 4.2.19 on 2025-02-12 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=255, unique=True)),
                ('ship_type', models.CharField(max_length=100)),
                ('capacity', models.FloatField()),
                ('flag', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ships',
            },
        ),
        migrations.CreateModel(
            name='ShippingLiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_details', models.TextField()),
                ('fleet_size', models.IntegerField()),
                ('operational_area', models.CharField(max_length=255)),
                ('type_of_vessels', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shippingliners',
            },
        ),
        migrations.CreateModel(
            name='ShippingRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_model', models.CharField(choices=[('per_teu', 'Per TEU'), ('per_ton', 'Per Ton'), ('flat_rate', 'Flat Rate')], max_length=100)),
                ('departure_schedule', models.JSONField()),
                ('arrival_schedule', models.JSONField()),
                ('liner_vessel_types', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.ship')),
            ],
            options={
                'db_table': 'shipping_routes_rel',
            },
        ),
        migrations.AddField(
            model_name='ship',
            name='shipping_liner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='shipping.shippingliner'),
        ),
    ]
