# Generated by Django 3.1.2 on 2025-02-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_auto_20250213_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='preferred_fuel_type',
            field=models.CharField(default='Diesel', max_length=50),
        ),
    ]
