# Generated by Django 4.2.19 on 2025-02-22 06:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_alter_ship_id_alter_shippingliner_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingroutes',
            name='arrival_schedule',
        ),
        migrations.RemoveField(
            model_name='shippingroutes',
            name='departure_schedule',
        ),
        migrations.AddField(
            model_name='shippingroutes',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 22, 6, 29, 26, 387149, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingroutes',
            name='departure_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
