# Generated by Django 4.2.19 on 2025-02-23 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_remove_shippingroutes_arrival_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingroutes',
            name='pricing_model',
        ),
        migrations.AddField(
            model_name='shippingroutes',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shippingroutes',
            name='voyage_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
