# Generated by Django 4.2.19 on 2025-02-16 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_type', models.CharField(choices=[('fabrics', 'Fabrics'), ('electronics', 'Electronics'), ('machinery', 'Machinery'), ('general', 'General Cargo'), ('hazardous', 'Hazardous Materials'), ('refrigerated', 'Refrigerated Goods')], max_length=50)),
                ('is_temperature_controlled', models.BooleanField(default=False)),
                ('is_dangerous', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('earliest_departure_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_type_size', models.CharField(choices=[('20ft_standard', '20ft Standard Container'), ('40ft_standard', '40ft Standard Container'), ('20ft_reefer', '20ft Refrigerated Container'), ('40ft_reefer', '40ft Refrigerated Container'), ('flat_rack', 'Flat Rack Container'), ('open_top', 'Open Top Container'), ('tank', 'Tank Container'), ('custom', 'Custom Size')], max_length=50)),
                ('number_of_containers', models.IntegerField()),
                ('weight_per_container', models.FloatField()),
                ('container_usage_options', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='cargo.cargo')),
            ],
            options={
                'db_table': 'container',
            },
        ),
    ]
