# Generated by Django 4.2.19 on 2025-03-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='dg_class',
            field=models.CharField(blank=True, choices=[('class_1', 'Explosives'), ('class_2', 'Gases'), ('class_3', 'Flammable Liquids'), ('class_4', 'Flammable Solids'), ('class_5', 'Oxidizing Substances'), ('class_6', 'Toxic & Infectious Substances'), ('class_7', 'Radioactive Materials'), ('class_8', 'Corrosives'), ('class_9', 'Miscellaneous Dangerous Goods')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='hazardous_level',
            field=models.CharField(blank=True, choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='temperature_range',
            field=models.CharField(blank=True, choices=[('cold', 'Cold (-20°C to 0°C)'), ('cool', 'Cool (0°C to 8°C)'), ('ambient', 'Ambient (15°C to 25°C)'), ('hot', 'Hot (Above 25°C)')], max_length=20, null=True),
        ),
    ]
