# Generated by Django 4.2.19 on 2025-03-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_cargo_dg_class_cargo_hazardous_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='is_dangerous',
            new_name='dangerous_goods',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='is_temperature_controlled',
            new_name='temperature_controlled',
        ),
    ]
